### ISSUE TITLE
It doesn't compile, probably missing a commit?

### ISSUE THREAD

**Issue by haschdl** [johnalexandergreene/Geom_Kisrhombille#1]
Hello! What a fascinating piece! While the information in the readme is very informative, I wasn't able to compile the library.  For example  `getInteriorPoints()` doesn't have any implementation, and compilation fails with `Error:(244, 3) java: missing return statement`. 

```Java
 /**
   * @return all points that are inside the area of the polygon (including points that are on the polygon edge)
   * 
   * For each interior seg
   * get all of the points it crosses. Not just the end points but also the points in between the end points.
   * Put them in a set.
   * 
   * We return a copy of the cached interiorpoints, for security.
   */
  public Set<KPoint> getInteriorPoints(){
    
  }
````

**Comment by johnalexandergreene** [comment]
It looks like something I never wrote.
The Geom_Kisrhombille package is a bit messy.
